name: CI
on: pull_request
jobs:
  build:
    name: Pull Request Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
